POST http://127.0.0.1:4000/bags/bagItem HTTP/1.1
content-type: application/json

{
    "name": "pro6",
    "image": "test",
    "client": 12345
}

###

Get http://127.0.0.1:4000/bags/pack HTTP/1.1
content-type: application/json

{
    "client" :123456
}


###

Delete http://127.0.0.1:4000/bags/615de01fde472577fceb08ce HTTP/1.1
content-type: application/json

{
    "id" :"615de01fde472577fceb08ce"
}

